# fly.toml app configuration file generated for llm-client on 2023-09-16T03:42:55-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "llm-client"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
